name: terraform

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/terraform.yaml
      - '**/*.tf'
      - '**/.terraform.*'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: sudo chmod -R ugo+rwX .
      - run: make
      - uses: int128/update-generated-files-action@v2

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-docs/gh-actions@v1
      - run: sudo chmod -R ugo+rwX .
      - uses: int128/update-generated-files-action@v2
